# TEST PACKAGE

In [31]:
import sklearn
sklearn.__version__

'0.22.1'

In [4]:
import scipy

In [5]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt

In [7]:
import scrapy

ModuleNotFoundError: No module named 'scrapy'

In [8]:
from bs4 import BeautifulSoup

ModuleNotFoundError: No module named 'bs4'

In [9]:
import bokeh

ModuleNotFoundError: No module named 'bokeh'

In [10]:
import cartopy

ModuleNotFoundError: No module named 'cartopy'

In [11]:
import seaborn

In [12]:
import sqlite3

In [13]:
import pandas as pd

In [14]:
import sklearn

In [15]:
import rpy2

ModuleNotFoundError: No module named 'rpy2'

In [16]:
import sqlalchemy

In [17]:
import pymysql

In [18]:
%load_ext sql

In [19]:
%sql sqlite:///lahman2016.sqlite

'Connected: @lahman2016.sqlite'

In [20]:
%%sql 
/* take a peek at the full sqlite_master table */
SELECT * 
FROM sqlite_master

 * sqlite:///lahman2016.sqlite
Done.


[]

In [21]:
import category_encoders

ModuleNotFoundError: No module named 'category_encoders'

In [22]:
import xgboost

In [23]:
from graphviz import Digraph

In [1]:
import pydotplus

In [25]:
from tpot import TPOTClassifier
from tpot import TPOTRegressor

ModuleNotFoundError: No module named 'tpot'

In [26]:
import nltk

ModuleNotFoundError: No module named 'nltk'

In [27]:
from nltk.corpus import brown

ModuleNotFoundError: No module named 'nltk'

In [28]:
import re

In [29]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')


In [30]:

print(mnist.data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
import xlrd

In [34]:
import textacy

ModuleNotFoundError: No module named 'textacy'

In [ ]:
text = ("my text1"
        "my text2")

doc = textacy.make_spacy_doc(text)

en = textacy.load_spacy_lang("en")